name: "🧹 Chore"
description: What are we building?
title: "🧹 [CHORE]: "
labels: "chore"
projects: ["dgrebb.com"]
assignees:
  - dgrebb
body:
  - type: textarea
    id: summary
    attributes:
      label: "Summary"
      description: Provide a brief explanation of the chore
    validations:
      required: true
  - type: textarea
    id: tasks
    attributes:
      label: Tasks
      value: "- [ ] "
    validations:
      required: false
