name: "Install and Cache Dependencies"
description: "Sets up caches and/or installs project dependencies."
author: dgrebb

inputs:
  WORKSPACE_ROOT:
    description: Working Directory

runs:
  using: composite
  steps:
    - name: ⚄ Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8

    - name: ⬢ Setup Node & pnpm Cache
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: pnpm
        cache-dependency-path: |
          ${{ inputs.WORKSPACE_ROOT }}/package.json
          ${{ inputs.WORKSPACE_ROOT }}/pnpm-lock.yaml
          ${{ inputs.WORKSPACE_ROOT }}/node_modules

    - name: 🎭 Install & Cache Playwright Binaries
      shell: bash
      working-directory: ${{ inputs.WORKSPACE_ROOT }}
      id: playwright-version
      run: echo 'PLAYWRIGHT_VERSION=$(cat package.json | jq -r '.dependencies.playwright' || 'latest')' >> $GITHUB_ENV

    - uses: actions/cache@v3
      id: playwright-cache
      with:
        path: |
          ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-${{ env.PLAYWRIGHT_VERSION }}

    - shell: bash
      if: steps.playwright-cache.outputs.cache-hit != 'true'
      working-directory: ${{ inputs.WORKSPACE_ROOT }}
      run: npx playwright install --with-deps

    - shell: bash
      if: steps.playwright-cache.outputs.cache-hit != 'true'
      working-directory: ${{ inputs.WORKSPACE_ROOT }}
      run: npx playwright install-deps

    - name: ↧ Install Remaining Dependencies
      shell: bash
      working-directory: ${{ inputs.WORKSPACE_ROOT }}
      run: pnpm install
