name: Build & Deploy

on:
  workflow_dispatch:

  repository_dispatch:
    types:
      - strapi

jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Add Masks
        run: |
          echo "::add-mask::${{ github.token }}"
          echo "::add-mask::${{ secrets.PUBLIC_API_URL }}"
          echo "::add-mask::${{ secrets.API_KEY }}"
          echo "::add-mask::${{ secrets.PUBLIC_SENTRY_DSN }}"
          echo "::add-mask::${{ secrets.PUBLIC_ENV }}"

      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: dgrebb/dgrebb.com
          ref: develop
          token: ${{ github.token }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"

      - name: Set .env
        run: |
          touch front/.env
          # echo PUBLIC_API_URL=${{ secrets.PUBLIC_API_URL }} >> front/.env
          echo PUBLIC_API_URL=http://host.docker.internal:1337/api >> front/.env
          echo API_KEY=${{ secrets.API_KEY }} >> front/.env
          echo PUBLIC_SENTRY_DSN=${{ secrets.PUBLIC_SENTRY_DSN }} >> front/.env
          echo PUBLIC_ENV=${{ secrets.PUBLIC_ENV }} >> front/.env
          cat front/.env

      - name: Build
        run: |
          echo "Building..."
          cd front
          npm ci
          npm run build
