name: 📡 CMS Publish 

on:
  workflow_dispatch:

jobs:
  approve:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    concurrency:
      group: cms-publish
      cancel-in-progress: true

    steps:
      - name: ✓ Approve CMS Dispatch
        uses: dgrebb/manual-approval@0.2.0
        with:
          secret: ${{ github.TOKEN }}
          approvers: dgrebb
          minimum-approvals: 1
          issue-title: "Deploying ${{ github.ref_name }} via CMS Dispatch Event"
          issue-body: "Please approve or deny the deployment of version ${{ github.ref_name }}."
          exclude-workflow-initiator-as-approver: false
          additional-approved-words: y,a
          labels: 'publish'

  frontend:
    runs-on: ubuntu-latest

    steps:
      - name: 🛰️ Dispatch B&D FE
        run: |
          curl --location 'https://api.github.com/repos/dgrebb/dgrebb.com/actions/workflows/bd-fe.yml/dispatches' \
          -H 'Content-Type: application/json' \
          -H 'Accept: application/vnd.github+json' \
          -H 'Authorization: Bearer ${{ secrets.DISPATCH_TOKEN }}' \
          --data '{"ref": "${{ github.ref_name }}"}'
