name: 📡 CMS Publish

on:
  workflow_dispatch:
    branches: [main, develop]

jobs:
  approve:
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
      - name: ✓ Approve CMS Dispatch
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: dgrebb
          minimum-approvals: 1
          issue-title: "Deploying ${{ github.ref_name }} via CMS Dispatch Event"
          issue-body: "Please approve or deny the deployment of version ${{ github.ref_name }}."
          exclude-workflow-initiator-as-approver: false
          additional-approved-words: ""
          additional-denied-words: ""

  frontend:
    runs-on: ubuntu-latest

    steps:
      - name: 🛰️ Dispatch B&D FE
        run: |
          curl -X POST https://api.github.com/repos/dgrebb/dgrebb.com/actions/workflows/bd-fe.yml/dispatches \
          -H 'Accept: application/vnd.github+json' \
          -H 'Authorization: Bearer ${{ secrets.DISPATCH_TOKEN }}' \
          --data '{"ref": "${{ github.ref_name }}"}'
