name: 🔀 B&D FE Merge

on:
  push:
    branches:
      - main
      - develop

jobs:

  frontend:
    runs-on: ubuntu-latest

    steps:

      - name: Dispatch Frontend
        run: |
          curl -X POST https://api.github.com/repos/dgrebb/dgrebb.com/actions/workflows/${{ secrets.FRONTEND_WORKFLOW_ID }}/dispatches \
          -H 'Accept: application/vnd.github+json' \
          -H 'Authorization: Bearer ${{ secrets.DISPATCH_TOKEN }}' \
          --data '{"ref": "${{ github.ref_name }}"}'
