name: 🧺 Lint 
run-name: "${{ github.ref_name == 'main' && 'PRD' || 'STG' }} - 🧼 Linting ${{ github.event_name == 'pull_request' && format('PR #{0}: {1}', github.event.pull_request.number, github.event.pull_request.title) || format('latest {0}', github.ref_name) }}"

on:
  workflow_dispatch:
  workflow_call:

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  lint:
    name: 💅 Prettier
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name == 'main' && 'prd' || 'stg' }}

    steps:
      - name: 𐂷 Checkout
        uses: actions/checkout@v3
        with:
          repository: dgrebb/dgrebb.com
          ref: ${{ github.ref }}
          token: ${{ github.token }}
          sparse-checkout: |
            front

      - name: ⬢ Setup Node & Cache
        uses: actions/setup-node@v3
        with:
          node-version: "18.18.0"
          cache: "npm"
          cache-dependency-path: |
            front/package.json
            front/package-lock.json
            front/node_modules

      - name: ↧ Install & Patch
        run: cd front && npm ci

      - name: 👓 Check
        run: |
          cd front && npm run lint
