name: 🧺 Lint
run-name: "${{ inputs.env == 'prd' && 'PRD' || 'STG' }} - 🧼 Linting ${{ github.event_name == 'pull_request' && format('PR #{0}: {1}', github.event.pull_request.number, github.event.pull_request.title) || format('latest {0}', github.ref_name) }}"

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      env:
        description: "Target deployment environment."
        type: string
        required: true

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
  NODE_VERSION: 20

jobs:
  lint:
    name: ≅ Lint
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.env }}
      url: "https://${{ vars.WWW_DOMAIN }}"

    steps:
      - name: 𐂷 Checkout
        uses: actions/checkout@v4
        with:
          repository: dgrebb/dgrebb.com
          ref: ${{ github.ref }}
          token: ${{ github.token }}
          fetch-depth: 1
          sparse-checkout: |
            .github/actions
            front

      - name: 🛢 Install Dependencies
        uses: ./.github/actions/install-cache-deps
        with:
          WORKSPACE_ROOT: front

      - name: 👓 Check
        run: |
          cd front && pnpm check && pnpm lint
