name: Release Dispatch

on:
  push:
    branches:
      - release/**
  pull_request:
    branches:
      - main

jobs:

  release:
    runs-on: ubuntu-latest

    steps:

      - name: Dispatch Frontend
        run: |
          curl -X POST https://api.github.com/repos/dgrebb/dgrebb.com/actions/workflows/${{ secrets.FRONTEND_WORKFLOW_ID }}/dispatches \
          -H 'Accept: application/vnd.github+json' \
          -H 'Authorization: Bearer ${{ secrets.DISPATCH_TOKEN }}' \
          --data '{"ref": "${{ github.ref_name }}"}'
