name: 🎯 Submit Sitemap Updates

on:
  workflow_dispatch:
  workflow_call:

jobs:
  ping:
    name: 🏓 Ping Google
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.env }}
      url: "https://${{ vars.WWW_DOMAIN }}"

    steps:
      - name: Send HTTP GET request
        if: ${{ github.ref_name == 'main'}}
        run: curl http://www.google.com/ping?sitemap=https://www.dgrebb.com/sitemap.xml
