name: 🔬 Test Front End Performance
run-name: "${{ github.ref_name == 'main' && 'PRD' || 'STG' }} - Test Performance of ${{ github.event_name == 'pull_request' && format('PR #{0}: {1} on ', github.event.pull_request.number, github.event.pull_request.title) || format('latest `{0}` in ', github.ref_name) }}"

on:
  workflow_call:
    secrets:
      REPORTS_AWS_S3_BUCKET:
        required: true
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_REGION:
        required: true
  workflow_dispatch:
  # pull_request:
  #   paths:
  #     - "front/**"
  #   branches: [main, develop]

permissions:
  checks: write
  contents: write

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: ⛵️ Audit URLs using Lighthouse
        id: lighthouse
        uses: treosh/lighthouse-ci-action@v10
        with:
          urls: |
            https://stg.dgrebb.com/
          # budgetPath: ./budget.json # test performance budgets
          # uploadArtifacts: true # save results as an action artifacts
          temporaryPublicStorage: true # upload lighthouse report to the temporary storage

      - name: Upload Lighthouse Report
        run: |
          echo 'hello world'
          echo ${{ steps.lighthouse.outputs.resultsPath }}
