name: 🔍 PageSpeed Insights
run-name: "${{ inputs.env == 'prd' && 'PRD' || 'STG' }} - PSI Run for ${{ github.event_name == 'pull_request' && format('PR #{0}: {1}', github.event.pull_request.number, github.event.pull_request.title) || format('latest {0}', github.ref_name) }}"

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      env:
        description: "Target deployment environment."
        type: string
        required: true
    secrets:
      PSI_APIKEY:
        required: true
      GH_WORKFLOW_TOKEN:
        required: true

permissions:
  checks: write
  contents: write

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  psi:
    name: 📊 Page Speed Insights
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.env }}
      url: "https://${{ vars.WWW_DOMAIN }}"

    steps:
      - name: 𐂷 Checkout
        uses: actions/checkout@v4
        with:
          repository: dgrebb/dgrebb.com
          ref: ${{ github.ref }}
          token: ${{ github.token }}
          fetch-depth: 1
          sparse-checkout: |
            _ci/_utils
            _ci/perf

      - name: ⚄ Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: ⬢ Setup Node & Cache
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"
          cache-dependency-path: |
            _ci/perf/package.json
            _ci/perf/pnpm-lock.yaml
            _ci/perf/node_modules

      - name: ↧ Install & Patch
        run: |
          cd _ci/perf && pnpm i

      - name: 🌤️ Warmup CloudFront Cache
        run: |
          _ci/_utils/warmup.sh ${{ github.ref_name == 'main' && 'prd' || 'stg' }}

      - name: PSI Mobile
        run: |
          cd _ci/perf
          pnpm --reporter=silent psi ${{ github.ref_name == 'main' && 'https://www.dgrebb.com/?roboto' || 'https://stg.dgrebb.com/?roboto' }} --key=${{ secrets.PSI_APIKEY }} --prettyprint=true --strategy=mobile >> $GITHUB_STEP_SUMMARY

      - name: PSI Desktop
        run: |
          cd _ci/perf
          pnpm --reporter=silent psi ${{ github.ref_name == 'main' && 'https://www.dgrebb.com/?roboto' || 'https://stg.dgrebb.com/?roboto' }} --key=${{ secrets.PSI_APIKEY }} --prettyprint=true --strategy=desktop >> $GITHUB_STEP_SUMMARY
