name: ⛵️ Lighthouse - Tests
run-name: "${{ github.ref_name == 'main' && 'PRD' || 'STG' }} - Lighthouse Run for ${{ github.event_name == 'pull_request' && format('PR #{0}: {1}', github.event.pull_request.number, github.event.pull_request.title) || format('latest {0}', github.ref_name) }}"

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      REPORTS_AWS_S3_BUCKET:
        required: true
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_REGION:
        required: true
  # pull_request:
  #   paths:
  #     - "front/**"
  #   branches: [main, develop]

permissions:
  checks: write
  contents: write

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  lighthouse:
    name: ⛵️ Running Audit on ${{ github.ref_name == 'main' && 'PRD' || 'STG' }}
    runs-on: ubuntu-latest

    environment:
      name: ${{ github.ref_name == 'main' && 'prd' || 'stg' }}

    steps:
      - name: 𐂷 Checkout
        uses: actions/checkout@v3
        with:
          repository: dgrebb/dgrebb.com
          ref: ${{ github.ref }}
          token: ${{ github.token }}
          sparse-checkout: |
            _ci

      - name: 🌤️ Warmup Cache
        run: |
          _ci/_utils/warmup.sh
          echo "# Lighthouse Reports" >> $GITHUB_STEP_SUMMARY
          echo "<a href=\"http://${{ vars.REPORTS_DOMAIN }}/lighthouse\" target=\"_blank\">Lighthouse Reports</a>" >> $GITHUB_STEP_SUMMARY

      - name: 🔦 Run Lighthouse
        id: lighthouse
        uses: treosh/lighthouse-ci-action@v10
        with:
          configPath: "../_ci/perf/lighthouse/.lighthouserc.json"
          urls: |
            https://${{ vars.WWW_DOMAIN }}/
            https://${{ vars.WWW_DOMAIN }}/posts
            https://${{ vars.WWW_DOMAIN }}/post/the-little-end-to-end-testing-engineer-who-could-a-tale-of-heroism-and-headaches/
            https://${{ vars.WWW_DOMAIN }}/posts/category/development/
            https://${{ vars.WWW_DOMAIN }}/privacy

      - name: ⚓️ Drop Anchor
        run: _ci/perf/_utils/landfall.sh ${{ steps.lighthouse.outputs.resultsPath }}

      - name: ⬆ Upload Reports
        if: always()
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete --cache-control max-age=2853200,public
        env:
          AWS_S3_BUCKET: ${{ vars.REPORTS_DOMAIN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SOURCE_DIR: ${{ steps.lighthouse.outputs.resultsPath }}
          DEST_DIR: "lighthouse"
