name: 🔍 PageSpeed Insights
run-name: "${{ github.ref_name == 'main' && 'PRD' || 'STG' }} - PSI Run for ${{ github.event_name == 'pull_request' && format('PR #{0}: {1}', github.event.pull_request.number, github.event.pull_request.title) || format('latest {0}', github.ref_name) }}"

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      PSI_APIKEY:
        required: true
      GH_WORKFLOW_TOKEN:
        required: true

permissions:
  checks: write
  contents: write

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  psi:
    name: 📊 Page Speed Insights
    runs-on: ubuntu-latest

    environment:
      name: ${{ github.ref_name == 'main' && 'prd' || 'stg' }}

    steps:
      - name: 𐂷 Checkout
        uses: actions/checkout@v3
        with:
          repository: dgrebb/dgrebb.com
          ref: ${{ github.ref }}
          token: ${{ github.token }}
          sparse-checkout: |
            _ci/_utils
            _ci/perf

      - name: ⬢ Setup Node & Cache
        uses: actions/setup-node@v3
        with:
          node-version: "18.18.2"
          cache: "npm"
          cache-dependency-path: |
            _ci/perf/package.json
            _ci/perf/package-lock.json
            _ci/perf/node_modules

      - name: ↧ Install & Patch
        run: |
          cd _ci/perf && npm ci

      - name: 🌤️ Warmup CloudFront Cache
        run: |
          _ci/_utils/warmup.sh ${{ github.ref_name == 'main' && 'prd' || 'stg' }}

      - name: PSI Mobile
        run: |
          cd _ci/perf
          npm run -s psi -- ${{ github.ref_name == 'main' && 'https://www.dgrebb.com/?roboto' || 'https://stg.dgrebb.com/?roboto' }} --key=${{ secrets.PSI_APIKEY }} --prettyprint=true --strategy=mobile >> $GITHUB_STEP_SUMMARY

      - name: PSI Desktop
        run: |
          cd _ci/perf
          npm run -s psi -- ${{ github.ref_name == 'main' && 'https://www.dgrebb.com/?roboto' || 'https://stg.dgrebb.com/?roboto' }} --key=${{ secrets.PSI_APIKEY }} --prettyprint=true --strategy=desktop >> $GITHUB_STEP_SUMMARY

      # - name: PageSpeed Insights Mobile
      #   id: psim
      #   uses: stefafafan/psi-action@v1
      #   with:
      #     url: ${{ github.ref_name == 'main' && 'https://www.dgrebb.com/?roboto' || 'https://stg.dgrebb.com/?roboto' }}
      #     key: ${{ secrets.PSI_APIKEY }}
      #     strategy: "mobile"

      # - name: PageSpeed Insights Desktop
      #   id: psid
      #   uses: stefafafan/psi-action@v1
      #   with:
      #     url: ${{ github.ref_name == 'main' && 'https://www.dgrebb.com/?roboto' || 'https://stg.dgrebb.com/?roboto' }}
      #     key: ${{ secrets.PSI_APIKEY }}
      #     strategy: "desktop"