name: 🧪 Test Front End

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "front/**"
    branches: [main, develop]

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  visual_regression:
    name: 🙈 BackstopJS
    runs-on: ubuntu-latest

    concurrency:
      group: tests
      cancel-in-progress: true

    # outputs:
    #   RELEASE_NAME: ${{ steps.vars.outputs.RELEASE_NAME }}
    #   DIST: ${{ steps.vars.outputs.DIST }}

    environment:
      name: ${{ github.ref_name == 'main' && 'production' || 'staging' }}

    env:
      DEPLOY_ENV: ${{ github.ref_name == 'main' && 'production' || 'staging' }}
      GH_TOKEN: ${{ github.token }}

    steps:
      - name: 🏃 Create Check Run
        # https://www.kenmuse.com/blog/creating-github-checks/
        run: |
          gh api -X POST -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${{ github.repository }}/check-runs
            --input - <<- EOF
              {
                "name: "BackstopJS",
                "head_sha": "${{ github.event.pull_request.head.sha }}",
                "status": "queued",
                "output": {
                    "title": "Starting Visual Regression",
                    "summary": "Heating up some ramen."
                }
              }
          EOF

      - name: 𐂷 Checkout
        uses: actions/checkout@v3
        with:
          repository: dgrebb/dgrebb.com
          ref: ${{ github.ref }}
          token: ${{ github.token }}
          fetch-depth: 0

      - name: ⬢ Setup Node & Cache
        uses: actions/setup-node@v3
        with:
          node-version: "18.17.1"
          cache: "npm"
          cache-dependency-path: _ci/backstop/package-lock.json

      - name: ↧ Install & Patch
        run: cd _ci/backstop && npm ci

      - name: Start Check
        # https://www.kenmuse.com/blog/creating-github-checks/
        run: |
          gh api -X POST -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${{ github.repository }}/check-runs
            --input - <<- EOF
              {
                "head_sha": "${{ github.event.pull_request.head.sha }}",
                "status": "in_progress",
                "output": {
                    "title": "Running Visual Regression 🪤"
                }
              }
          EOF

      - name: ⌛️ Running Visual Regression
        id: backstop
        run: cd _ci/backstop && ENV=$DEPLOY_ENV npm run test

      - name: Complete Check
        env:
          RESULT: "${{ steps.backstop.conclusion && '❌' || '✅' }}"
        run: |
          gh api -X POST -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${{ github.repository }}/check-runs
            --input - <<- EOF
              {
                "name: "BackstopJS",
                "head_sha": "${{ github.event.pull_request.head.sha }}",
                "status": "complete",
                "output": {
                    "title": "Visual Regression Complete $RESULT",
                    "summary": "Here's where we'll list the failed tests."
                }
              }
          EOF

      - name: ❌ Fail
        if: failure()
        run: echo 'oh noes! something went horribly wrong.'

      - name: ✅ Success
        run: echo 'let us continue.'
