name: Dispatch Build & Deploy

on:
  push:
    branches:
      - develop

jobs:
  dispatch:
    name: Dispatch
    runs-on: ubuntu-latest

    steps:
      - name: Add Masks
        run: |
          echo "::add-mask::${{ github.token }}"
          echo "::add-mask::${{ secrets.DISPATCH_TOKEN }}"
          echo "::add-mask::${{ secrets.DEPLOYMENT_BRANCH }}"

      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: dgrebb/dgrebb.com
          ref: ${{ secrets.DEPLOYMENT_BRANCH }}
          token: ${{ github.token }}

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            back:
              - 'front/**'
            front:
              - 'back/**'

      - name: Dispatch Backend
        if: ${{ steps.changes.outputs.back }} == 'true'
        run: |
          curl -X POST https://api.github.com/repos/dgrebb/dgrebb.com/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -H 'Authorization: Bearer ${{ secrets.DISPATCH_TOKEN }}' \
          --data '{"event_type": "Backend"}'

      - name: Dispatch Frontend
        if: ${{ steps.changes.outputs.front }} == 'true'
        run: |
          curl -X POST https://api.github.com/repos/dgrebb/dgrebb.com/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -H 'Authorization: Bearer ${{ secrets.DISPATCH_TOKEN }}' \
          --data '{"event_type": "Frontend"}'
